services:
  shortique:
    image: ghcr.io/hedlx/shortique:latest
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS=redis:6379
      - TOKEN=%TELEGRAM_BOT_TOKEN%
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
