version: '3.6'

services:
  shortique:
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - "${PWD}/.env:/.env"
    environment:
      - REDIS=redis:6379
  redis:
    image: "redis:6-alpine"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
    redis_data:
